---
- name: "Install EPEL"
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: "Install nginx"
  yum:
    name: nginx
    state: present
- name: "Copy configuration"
  template:
    src: ../templates/nginx.conf
    dest: /etc/nginx/conf.d/nginx.conf
- name: "Restart nginx"
  service:
    name: nginx
    state: restarted